### ISSUE TITLE
Messages not being shown when multiple are sent at once

### ISSUE THREAD

**Issue by VietnamNeko** [moddio/taro2#380]
![image](https://user-images.githubusercontent.com/58660787/235468490-8a2f565a-b48f-4e43-9e56-7aa67396f627.png)
when multiple chat messages are sent at once only the latest seems to be displayed.

**Comment by pranshu6** [comment]
Thanks for the report. We pushed a fix, that will solve the issue. 

Thanks @420kyle69 for the suggestion - 
https://www.modd.io/forum/t/sending-multiple-chat-messages-at-the-same-time-only-shows-the-last-message-sent/2519/4

Let me know if you or anyone still faces the issue or else we can close the issue.
